---
- hosts: wordpress
  become: true
  tasks:
    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present
      tags: install

    - name: Install Docker SDK and requests
      pip:
        name:
          - docker
          - requests
        executable: pip3
      tags: install

    - name: Create Docker network for WordPress 2
      community.docker.docker_network:
        name: wordpress2-net
        state: present

    - name: Pull MySQL image
      community.docker.docker_image:
        name: mysql
        tag: "5.7"
        source: pull

    - name: Run MySQL container for WP2
      community.docker.docker_container:
        name: wordpress2-db
        image: mysql:5.7
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: example_root_password
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress_user
          MYSQL_PASSWORD: wordpress_password
        networks:
          - name: wordpress2-net
        volumes:
          - wordpress2-db-data:/var/lib/mysql

    - name: Pull WordPress image
      community.docker.docker_image:
        name: wordpress
        source: pull

    - name: Run WordPress container for WP2
      community.docker.docker_container:
        name: wordpress2
        image: wordpress
        state: started
        restart_policy: always
        env:
          WORDPRESS_DB_HOST: wordpress2-db       # fixed: no port
          WORDPRESS_DB_USER: wordpress_user
          WORDPRESS_DB_PASSWORD: wordpress_password
          WORDPRESS_DB_NAME: wordpress
        ports:
          - "8082:80"
        networks:
          - name: wordpress2-net
        volumes:
          - wordpress2-data:/var/www/html
