---
- hosts: wordpress
  become: true
  vars:
    wp_index: 1  # default if not provided
    wp_db_name: "wordpress"
    wp_db_user: "wordpress_user"
    wp_db_pass: "wordpress_password"
    wp_root_pass: "example_root_password"
  tasks:
    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK and requests
      pip:
        name:
          - docker
          - requests
        executable: pip3

    - name: Create Docker network for WordPress instance
      community.docker.docker_network:
        name: "wordpress{{ wp_index }}-net"
        state: present

    - name: Pull MySQL image
      community.docker.docker_image:
        name: mysql
        tag: "5.7"
        source: pull

    - name: Run MySQL container for WP instance
      community.docker.docker_container:
        name: "wordpress{{ wp_index }}-db"
        image: mysql:5.7
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: "{{ wp_root_pass }}"
          MYSQL_DATABASE: "{{ wp_db_name }}"
          MYSQL_USER: "{{ wp_db_user }}"
          MYSQL_PASSWORD: "{{ wp_db_pass }}"
        networks:
          - name: "wordpress{{ wp_index }}-net"
        volumes:
          - "wordpress{{ wp_index }}-db-data:/var/lib/mysql"

    - name: Pull WordPress image
      community.docker.docker_image:
        name: wordpress
        source: pull

    - name: Run WordPress container for WP instance
      community.docker.docker_container:
        name: "wordpress{{ wp_index }}"
        image: wordpress
        state: started
        restart_policy: always
        env:
          WORDPRESS_DB_HOST: "wordpress{{ wp_index }}-db"
          WORDPRESS_DB_USER: "{{ wp_db_user }}"
          WORDPRESS_DB_PASSWORD: "{{ wp_db_pass }}"
          WORDPRESS_DB_NAME: "{{ wp_db_name }}"
        ports:
          - "{{ 8080 + wp_index | int }}:80"
        networks:
          - name: "wordpress{{ wp_index }}-net"
        volumes:
          - "wordpress{{ wp_index }}-data:/var/www/html"
